CREATE TABLE IF NOT EXISTS checkins(
  id INTEGER PRIMARY KEY,
  date TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS foods(
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  calories REAL NOT NULL,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS workouts(
  id INTEGER PRIMARY KEY,
  title TEXT NOT NULL,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS media(
  id INTEGER PRIMARY KEY,
  key TEXT NOT NULL,
  created_at TEXT NOT NULL
);
