
CREATE TABLE IF NOT EXISTS checkins(id INTEGER PRIMARY KEY, checkin_date TEXT);
CREATE TABLE IF NOT EXISTS workouts(id INTEGER PRIMARY KEY, title TEXT);
CREATE TABLE IF NOT EXISTS foods(id INTEGER PRIMARY KEY, name TEXT, calories REAL);
CREATE TABLE IF NOT EXISTS media(id INTEGER PRIMARY KEY, file_key TEXT);
